/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 7b1543983ca2c7b9dd0254d17d984ce0)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "DirectorAgent";
  }
  interface Env {
    AI: Ai;
    DirectorAgent: DurableObjectNamespace<import("./src/server").DirectorAgent>;
  }
}
interface Env extends Cloudflare.Env {}
